server:
  port: 9001
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
#feign:
#  httpclient:
#    enabled: true
#  hystrix:
#    enabled: true
#    execution:
#      timeout:
#        enabled: false
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
#    HystrixCommandKey:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
#请求处理的超时时间
ribbon:
  ReadTimeout: 130000
  #请求连接的超时时间
  ConnectTimeout: 10000
spring:
  application:
    name: front-service
  output:
    ansi:
      enabled: always
  profiles:
    active: #{spring.profiles.active}
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 20MB
  devtools:
    restart:
      enabled: false
logging:
  level:
     cn.comtom.ebs.front: debug
