spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    quartz:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initialize: true
      name: sky
      jdbc-url: jdbc:mysql://127.0.0.1:3306/cz_eb_dev?zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:9999/eureka/