dynamic:
  host-ip: 192.168.111.116
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    quartz:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initialize: true
      name: sky
      jdbc-url: jdbc:mysql://${dynamic.host-ip}:3306/cz_eb_dev?zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: comtom
      password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@${dynamic.host-ip}:9999/eureka/
