dynamic:
  host-ip: 192.168.111.116
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@${dynamic.host-ip}:9999/eureka/


cert:
  apply:
    url: http://124.127.49.183:809/MAV/zcqq
    cert: '000011010001'
